### PR TITLE
Reduce fog's footprint by bringing in only fog-aws

### PR DESCRIPTION
**Pull request by rpdillon**
Fog's readme suggests this:

> If there's a metagem available for your cloud provider, e.g. fog-aws,
> you should be using it instead of requiring the full fog collection to
> avoid unnecessary dependencies.

Since Redishifter is used on many production apps, this can be significant.

@jrichard @quarterdome 

I noticed this because of a change in API yesterday that required I update the fog-brightbox gem.

### CODE REVIEW

**Comment by rpdillon** [comment]
Should I version the gem as well?  I think this is mostly used straight from git, so I didn't bother.

**Comment by kristjan** [comment]
Rad, LGTM if that's all we need.

I'm pro-versioning. It's trivially easy and I much prefer git tags like `v0.1.0` over SHAs or branches.

**Comment by quarterdome** [comment]
Ah, awesome! 

It is used via Rubygems, so yes please version. It is a public gem after all, and all this conversation is public too :)

**Comment by rpdillon** [comment]
OK, I've bumped the version from 0.6.1 to 0.6.2.

**Comment by kristjan** [comment]
Still LGTM 👍  If any of you find a Chrome extension that will turn public repo backgrounds a different color, that would be excellent.

**Pull request merged**
